import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Grid, TextField} from '@mui/material'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Schoolbell&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main} style={{width:'100vw', padding: 50, justifyItems: 'flex-start'}}>
        <h1 className={styles.title}>
          UFO Detector
        </h1>
        <Grid container style={{margin: '20 10', paddingTop: '6rem'}}>
          <Grid style={{padding:'0 12px'}} inputProps={{fontFamily: 'Schoolbell Regular'}} component={TextField} md={9} fullWidth variant="standard" label="URL"/>
          <Grid style={{padding:'0 12px'}} component={TextField} md={3} fullWidth variant="standard" label="Portas"/>

        </Grid>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
